homebrew_installed_packages:
  - git
  - go
  - tmux
  - fig
  - maccy
  - rectangle
  - cmatrix
  - asciiquarium
  - toilet
  - espanso

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - firefox
  - licecap
  - slack
  - devtoys
  - iterm2
  - warp

configure_dock: true
dockitems_remove:
  - TV
  - Podcasts

dockitems_persist:
  - name: "Firefox"
    path: "/Applications/Firefox.app/"
    pos: 4

configure_dotfiles: true